# version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    environment:
      - VITE_API_BASE_URL=${VITE_API_BASE_URL}
    volumes:
      - ./ssl/datacorpsolutions.crt:/etc/ssl/certs/datacorpsolutions.crt
      - ./ssl/datacorpsolutions.key:/etc/ssl/private/datacorpsolutions.key
    networks:
      - frontend-network

networks:
  frontend-network:
    driver: bridge